#########################################
#   VARIABLES
##########################################

$mainMod = SUPER

##########################################
#   MONITORS
##########################################

monitor=Virtual-1,preferred,auto,1

##########################################
#   AUTOSTART
##########################################

exec-once = swww-daemon
exec-once = ~/.config/hypr/swww-random.sh
exec-once = waybar
exec-once = mako
exec-once = wl-paste --type text --watch cliphist store

##########################################
#   INPUT
##########################################

input {
    kb_layout = us
    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }
}

##########################################
#   GENERAL
##########################################

general {
    gaps_in = 2
    gaps_out = 8
    border_size = 2

    layout = dwindle
    allow_tearing = false
}

##########################################
#   DECORATION
##########################################

decoration {
    rounding = 2
}

##########################################
#   ANIMATIONS
##########################################

animations {
    enabled = yes
}


##########################################
#   KEYBINDS
##########################################

# Launch terminal
bind = $mainMod, T, exec, foot

# App launcher
bind = $mainMod, D, exec, wofi --show drun --style ~/.config/wofi/style.css 

# Close window
bind = $mainMod, Q, killactive

# Open File Manager
bind = $mainMod, E, exec,thunar

# Task Manager btop
bind = $mainMod, M, exec, foot -e btop

# Fullscreen
bind = $mainMod, SPACE, fullscreen

# Screenshot: select area
bind = , Print, exec, grim -g "$(slurp)" - | wl-copy

# ------------------------------
# TOGGLE SELECT 
# ------------------------------
bind = $mainMod, LEFT, movefocus, l
bind = $mainMod, RIGHT, movefocus, r
bind = $mainMod, UP, movefocus, u
bind = $mainMod, DOWN, movefocus, d

bind = $mainMod SHIFT, LEFT, movewindow, l
bind = $mainMod SHIFT, RIGHT, movewindow, r
bind = $mainMod SHIFT, UP, movewindow, u 
bind = $mainMod SHIFT, DOWN, movewindow, d

# RESIZE WINDOW
bind = $mainMod CTRL, UP, exec, hyprctl dispatch resizeactive 0 -40
bind = $mainMod CTRL, DOWN, exec, hyprctl dispatch resizeactive 0 40
bind = $mainMod CTRL, RIGHT, exec, hyprctl dispatch resizeactive 40 0
bind = $mainMod CTRL, LEFT, exec, hyprctl dispatch resizeactive -40 0

# Toggle Desktops
# Switch to workspace 1-9
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9

# Move window to workspace 1-9
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
